### PR TITLE
Added support to Multi-target regression

### PR DESCRIPTION
**Pull request by smastelini**
Greetings @scikit-multiflow/scikit-multiflow-repo-admins,

My name is Saulo Martiello Mastelini and I'm currently doing my PhD under the supervision of professor Andre Carlos Ponce de León Ferreira de Carvalho at Universidade de São Paulo - BR. I intend to research in multi-target regression (MTR) problems in data streams, as an extension of my MSc research.

I found very interesting the proposal of a Python solution for dealing with streaming tasks and I plan to contribute to this project as much as I can.

Therefore, I've implemented some extensions to your framework. They could be summarized as the addition of the iSoup-Tree algorithm for MTR problems (implemented in trees/multi_target_regression_hoeffding_tree.py by inheriting from regression_hoeffding_tree.py) and the modifications that this change brought with it.

It is worth mentioning that before attempting the pull request I've merged my local modifications with the last changes in the scikit-multiflow/MASTER repository.

I present a detailed summary of my implemented changes:
- I have added support to MTR error metrics in metrics/measure_collection.py
    - The new classes (MultiTargetRegressionMeasurements and WindowedMultiTargetRegressionMeasurements) implement the following error metrics: average Mean Squared Error (AMSE), average Mean Absolute Error (AMAE), and average Mean Square Error (ARMSE).
    - The necessary changes to evaluation/base_evaluator.py, evaluation/evaluate_prequential.py, and evaluation/evaluate_holdout.py were also implemented to ensure fully compatibility.

- I proposed and implemented a distinction among the types of the multi-output tasks:
    - New constants for MULTI_LABEL_CLASSIFICATION and MULTI_TARGET_REGRESSION were added to utils/constants.py
    - I've modified evaluation/base_evaluator.py to check for the type of multi-output tasks (please, refer to lines 220-229 of base_evaluator.py for an illustration).
    - Additionally, checks for the correct partial_fit method invocation were updated with the inclusion of MTR support (please, refer to lines 244-245 of evaluation/evaluate_prequential.py for an example of my modifications).
    - For future modifications, I suggest changing the names of the classes *MultiOutputMeasurements to *MultiLabelClassificationMeasurements.

- I created a new split criterion (trees/intra_cluster_variance_split_criterion.py) which implements the intra cluster variance reduction heuristic, as it is used in FIMT-MT and iSoup-Tree algorithms. My new class was created by inheriting from trees/variance_reduction_split_criterion.py.
    - The Intra Cluster Variance reduction is the default heuristic for MultiTargetRegressionHoeffdingTree.

- I also created a new numeric attribute class observer suited to multi-target regression problems. This new addition was implemented in trees/hoeffding_multi_output_numeric_attribute_observer.py by inheriting from AttributeClassObserver.
    - The original HoeffdingNumericAttributeClassObserver implementation presented some problems when used with MTR tasks, since it considered only a single-target. When checking for the best splits, the observer presented problems when dealing with the numpy.narrays which represent the targets. Copies of these structures were not made and the observer ended up using references to memory locations which not anymore represented the state of the statistics at the moment they were stored. Thus, I created a specific observer for MTR tasks.
    - My implementation considers the strategy presented in Osojnik's dissertation (where the author presents the iSoup-Tree algorithm). In this algorithm only the left statistics are stored instead of both the left and right ones (as proposed by Ikonomovska et al.). The author of the iSoup-Tree algorithm refers to these statistics as 'partial statistics'. The 'complete statistics' are calculated as the in-order binary tree search is performed. Combining this alternative strategy with extensive code profiling, I aimed at decreasing the time and memory footprints of the new observer.

- I also implemented the support to adaptive prediction model selection at the leaves, in detriment of exclusively using only Perceptrons or Targets' mean. The implementation is in conformation with MOA's implementation of the iSoup-Tree algorithm (Faded MAE is employed to select the best predictor for each target variable).

- I have created a demo file for testing the MTR implementation in demos/_test_mtr.py.

- I also added two test MTR datasets (scm1d and scm20d) and their references in data/datasets.

- I updated and/or created documentations for my code as much as I could. Besides, I have tried to leave comments in my code frequently.

In addition, I would like to remark that I've used numpy functions as often as possible to speed up the performed operations.

Thanks in advance for your attention. I hope I would be able to contribute more to this project in the future.

With regards,
Saulo

### CODE REVIEW

**Comment by jacobmontiel** [comment]
Hello Saulo (@smastelini),

Thanks for your contribution and the detailed explanation. I am writing some comments from the standpoint of the framework while @jmread can provide comments on the technical details.

- Could you add links to the files/lines you mention? This way it will be easier to follow your comments and we will ensure we are looking into the correct part of the code.

- Regarding the naming of constants and metrics class. What about this proposal for consistency:
  - MULTI_TARGET_CLASSIFICATION
  - MULTI_TARGET_REGRESSION
  - MultiTargetClassificationMeasurements

- Current tests are passing (thanks for keeping up with the master). But we need to add tests for the new code. 'demos' are used to show how the model should be used. On the other hand, 'tests' ensure functionality. You can check the test for Hoeffding Regression Trees as an example: https://github.com/scikit-multiflow/scikit-multiflow/blob/master/tests/trees/test_regression_hoeffding_tree.py
You can use the demos code as a  starting point to create the test. Once the test is ready, you can run 'pytest' from the main directory and should be automatically detected and evaluated.

- About the datasets. Is it possible to create a stream generator rather than keeping files? (Disclaimer: I am not familiar with the datasets)

Once again, thanks for your hard work. Let me know if you have any questions.

**Comment by smastelini** [comment]
Hi @jacobmontiel,

Thank you for the fast reply and help!

I will address your points as they were mentioned:

- Regarding the lines that I mentioned previously, the distinction between Multi-label (multi-target) classification and Multi-target regression was implemented as follows (the following chunk is performed after failing in checking if the stream is single-target):

https://github.com/scikit-multiflow/scikit-multiflow/blob/ada14e0f48ec7a871006571fbce6c5c9f2008b09/src/skmultiflow/evaluation/base_evaluator.py#L220-L229

Besides, as previously mentioned, I added some additional tests when calling the `partial_fit`:

https://github.com/scikit-multiflow/scikit-multiflow/blob/ada14e0f48ec7a871006571fbce6c5c9f2008b09/src/skmultiflow/evaluation/evaluate_prequential.py#L244-L249

- About the standards for the constants, I think your suggestion makes much more sense. If I may, I would happily implement those changes.

- Thanks for the suggestion. The mentioned example will be very useful. I will provide a test script to check the correct functioning of the new features added.

- The SCMDs datasets concern the prediction of multiple products' online sales. Those datasets belong to the most 'standard' multi-target regression benchmark set, which is available in the Mulan's website (http://mulan.sourceforge.net/datasets-mtr.html). Therefore, a generator could not be achieved for these specific problems. In batch scenarios those two datasets are among the most large available ones for MTR, but in data streams, in fact, they are among the smallest. That was my reasoning for choosing them. I can see some possible choices:
    - Choose one of those datasets (scm1d or scm20d), just to provide a way for running a demo script;
    - Use a sample of smaller size of them (I'm not sure about copyrights);
    - Reproduce a generator for some of the synthetic tasks that were performed in the literature (this option might be the best of the three).

What do you think?

Thank you again for your help!

**Comment by smastelini** [comment]
Greetings,

- I've changed the constants for the suggested pattern (MULTI_TARGET_CLASSIFICATION and MULTI_TARGET_REGRESSION).
- I also added a test script for the new functionalities (tests/trees/test_multi_target_regression_hoeffding_tree.py).
- I removed the previously added multi-target regression datasets. Now, the created demo script uses the 'RegressorGenerator'.

If there are any more changes to be applied I will be happy to implement them!

**Comment by jacobmontiel** [comment]
Hi @smastelini,

Thanks for the fast updates. Actually, I had to rewrite this message since you already covered some of the things I wrote :+1: 

Comments:

1) I forgot to mention the tests for the new metrics. The other measure collections are tested in:
https://github.com/scikit-multiflow/scikit-multiflow/blob/master/tests/metrics/test_measure_collection.py

2) You can confirm if the documentation of your code is rendered correctly by Sphinx by performing the steps described in https://github.com/scikit-multiflow/scikit-multiflow/blob/master/CONTRIBUTING.md#sphinx-documentation

Note: The command to use is outdated and should read:
```
sphinx-apidoc -o scikit-multiflow/docs scikit-multiflow/src/skmultiflow -e -f 
```
This will generate a local version of the documentation page in `scikit-multiflow/docs/build/_html`. 

Please, do not add any of the documentation files (in the `/docs` directory) to your pull request. I will generate them once the code is in the main branch.

**Comment by smastelini** [comment]
Thank you @jacobmontiel! I will provide the required changes ASAP.

**Comment by smastelini** [comment]
Hi again @jacobmontiel,

I think I've implemented all the necessary changes.

I also was able to generate the docs after some minor corrections in my source codes.

If there are any more modifications to be implemented, please let me now!

**Comment by jacobmontiel** [comment]
Thanks @smastelini 

Everything looks good and I have started the review on the latest version.

**Comment by smastelini** [comment]
Hi @jacobmontiel, 

- I  now deleted the .pycache folder. I apologize for not even perceiving that those files were being added in my commits.
- About the whitespaces, those changes were not intended. I believe that my text editor (Atom + the Flake8 plugin for PEP8) might have some participation on this occurrence. I apologize again, as I originally intended to modify the minimum possible amount of files.
- The commented code can be deleted. I will take care of it when adjusting the test files as required.
- I properly renamed the methods and changed them to read from .npy files, as suggested.

I'm ready to commit the changes presented so far, but I am not sure about who will take care of changing the observers names. Can I make those changes or the admin team will implement the standardization?

Thank you again @jacobmontiel for putting so much effort in helping me through this pull request. I hope that my future contributions will be more ponctual, not affecting the scikit-multiflow's core structure.

**Comment by jacobmontiel** [comment]
Hi @smastelini ,

Thanks for addressing the comments and for your patience. This effort is also helpful to us to streamline the PR process.

Regarding the renaming of attribute observers, I will create an issue to address it.

**Comment by jacobmontiel** [comment]
This PR is ready to be merged into the master.

- [x] Code complies with PEP-8 and is consistent with the framework.
- [x] Code is properly documented
- [x] Tests are included for new functionality
- [x] Travis CI build passes
- [x] Coverage is maintained (-0.16%)

Thanks @smastelini !

**Comment by smastelini** [comment]
Thanks @jacobmontiel for the fast and detailed responses, and also for your patience and guidance during the PR process!

**Pull request merged**
