### PR TITLE
Support Kafka integration. Decouple evaluation and reporting through observers. 

### PR DESCRIPTION
**Pull request by jmrozanec**
Changes proposed in this pull request:

* We support Kafka as events source
* We propose using data-sources to listen to events from any source. Data sources provide a stream of events, which we observe to train models and evaluate them based on different criteria (prequential, holdout (quantity and time based))
* We decouple train metrics computation from how are reported: this way, we can integrate with 3rd party tools to visualize metrics, persist/broadcast them where and when required, etc. We are no longer limited to the dashboard, file, and summarized info provided. 
* We introduce the mockito mocking library for tests to reduce the coupling of unnecessary elements for tests.
* We provide Dockerized environment for development, installing all required dependencies. This reduces setup requirements for developers, who can start working right away. The setup includes a docker instance with Kafka so that the Kafka integration can be verified/used.

---

#### Implementation
- [x] Implementation is correct (it performs its intended function).
- [x] Code is consistent with the framework.
- [ ] Code is properly documented.
- [ ] PR description covers ALL the changes performed.
- [x] Files changed (update, add, delete) are in the PR's scope (no extra files are included).

#### Tests
- [x] New functionality is tested.
- [x] Tests are created for the new functionality or existing tests are updated accordingly.
- [x] ALL tests pass with no errors.
- [ ] CI/CD pipelines run with no errors.
- [ ] Test Coverage is maintained (coverage may drop by no more than 0.2%).

### CODE REVIEW

**Comment by garawalid** [comment]
@jmrozanec thanks for this PR and the effort! 
This PR is big and difficult to review. Could you please divide it into small ones? You can keep the Docker environment the last one!  

Also, I think we need to discuss the design of the new API. What do you think?

**Comment by jmrozanec** [comment]
@garawalid it is difficult to split the change into smaller ones, at least for the Kafka support, since changes are all related. We already split the dev tools into #276, which is awaiting acceptance.

**Comment by garawalid** [comment]
@jmrozanec 
I'll review this PR ASAP. 

> Seems that in this PR, gh-actions do not detect the package structure changed, and fail due to that. Locally all tests pass. How can this be adjusted on PR checks?  

Do you run tests with an IDE (Pycharm for example) or directly with the command line?

**Comment by jmrozanec** [comment]
@garawalid we run them directly from the command line

**Comment by ahmed-masud** [comment]
Why not pull kafka through streamz? as suggested in https://github.com/scikit-multiflow/scikit-multiflow/issues/106

**Comment by jmrozanec** [comment]
> Why not pull kafka through streamz? as suggested in #106

@ahmed-masud because we already developed the feature before getting to know the #106 issue, and #106 was left half done - seems none is working on it or having the time to push it forward. We would be glad to work towards an implementation that can support integrations through and outside streamz as well.

**Pull request closed without merging**
