### PR TITLE
Convert ADWIN demo into Jupyter notebook

### PR DESCRIPTION
**Pull request by Payam-Ebadi**
Changes proposed in this pull request:

*The Python code transformed into jupyter notebook code 
* 
* Fixes # . [Optional]

---

Checklist

- [x] Code complies with PEP-8 and is consistent with the framework.
- [ ] Code is properly documented.
- [x] Tests are included for new functionality or updated accordingly.
- [ ] Travis CI build passes with no errors.
- [ ] Test Coverage is maintained (threshold is -0.2%).
- [x] Files changed (update, add, delete) are in the PR's scope (no extra files are included).

### CODE REVIEW

**Comment by jacobmontiel** [comment]
Hello Payam, could you update the description of the PR? Also, please mark the checklist items accordingly.

**Comment by Payam-Ebadi** [comment]
I did what you asked. If there is an issue just let me know!

**Comment by jacobmontiel** [comment]
Thbaks @Payam-Ebadi , a comment:

There are some typos in the description (both in the .py file and the notebook file). Here is a suggested edit:

```
In this demo, an ADWIN object evaluates a sequence of numbers corresponding to 2 distributions. The ADWIN object indicates the indices where change is detected.

The first half of the data is a sequence of randomly generated 0's and 1's. The second half of the data is a normal distribution of integers from 0 to 7.
```
Please update both files.

**Comment by jacobmontiel** [comment]
Thanks @Payam-Ebadi 

This demo provides insight on the effort required for #115

**Pull request merged**
