### PR TITLE
[FEATURE] Add AdaptiveRandomForestRegressor and streamline attribute observer for regression

### PR DESCRIPTION
**Pull request by smastelini**
This PR resumes the work (PR #145) started by Alban to implement the `AdaptiveRandomForestRegressor` (ARFReg). The implementation was finalized and tested. I have also added some additional options, such as different aggregation and weighting strategies, and different kinds of setups to track concept drifts.

As base learners, the Forest uses trees that derive from `HoeffdingTreeRegressor` (HTR), in detriment of FIMT-DD (as in MOA). HTRs do not have inner concept drift adaptation mechanisms; however, such action is performed at higher abstraction levels, by the ensemble algorithm. This action repeats in the classification version of Adaptive Random Forests.

In addition to ARFReg, this PR also streamlines the usage of attribute observers for regression. It adds a new and improved observer (derived from the multi-target regression observer) that works with both single-target and multi-target tasks. This enhanced `NumericAttributeRegressionObserver` also enables the support to instance weighting, an essential aspect for bagging-based algorithms. Hence, just a single observer is used for all the regression trees.

Changes proposed in this pull request:

* Finishes work initiated in PR #145
* Streamline regression observers

---

#### Implementation
- [x] Implementation is correct (it performs its intended function).
- [x] Code complies with PEP-8 and is consistent with the framework.
- [x] Code is properly documented.
- [x] PR description covers ALL the changes performed.
- [x] Files changed (update, add, delete) are in the PR's scope (no extra files are included).

#### Tests
- [x] New functionality is tested.
- [x] Tests are created for the new functionality or existing tests are updated accordingly.
- [x] ALL tests pass with no errors.
- [x] CI/CD pipelines run with no errors.
- [x] Test Coverage is maintained (coverage may drop by no more than 0.2%).

### CODE REVIEW

**Comment by jacobmontiel** [comment]
`test_hoeffding_tree_regressor_coverage` fails in Python 3.5. This seems related to the object size calculation. This is a known issue (#108 #111). We can deactivate the test for Python 3.5 or add some delta to account for the small difference.

**Comment by smastelini** [comment]
> test_hoeffding_tree_regressor_coverage fails in Python 3.5. This seems related to the object size calculation. This is a known issue (#108 #111). We can deactivate the test for Python 3.5 or add some delta to account for the small difference.

I vote to add a delta. What do you think?

**Comment by jacobmontiel** [comment]
Agree, a delta seems like a good compromise.

**Comment by smastelini** [comment]
> Agree, a delta seems like a good compromise.

I added a small tolerance in the failing test. It's working now :)

**Comment by smastelini** [comment]
The lack of coverage relates mainly to this portion:

https://github.com/smastelini/scikit-multiflow/blob/f0b060d1e6874f8f5b402a7c142693591c5f1460/src/skmultiflow/trees/attribute_observer/numeric_attribute_regression_observer.py#L160-L231

I have ported this helper function from the previous attribute observer. Nonetheless, none of the trees actually use it. This method removes potentially bad split candidates from the binary search tree using a bottom-up strategy.

**Comment by smastelini** [comment]
## Benchmark tests

I also performed some benchmark tests with the new implementation. Some tests are still running, and I'll update this message as they complete. I mainly used default parameters during the tests for both MOA and skmultiflow. I also set up MOA to use the same `delta` value applied in skmultiflow for the ADWIN objects (drift and warning detectors). In the following charts, I use the following notation:

* subscript `m`: indicates that the trees are using the target mean to provide responses at leaves.
* subscript `p`: the trees are using linear perceptrons to provide responses.
* the `w` prefix indicates that individual trees' responses are weighted (I setup the forests to use `mae` as the weighting scheme -- please refer to the documentation).
* unless otherwise stated (with the `+median` suffix), all forests are aggregating individual trees' predictions with the mean operation.
* the forests are monitoring the Mean Absolute Error to track concept drifts.

---

### Fried dataset

I started with the well-known synthetic task `Fried`. Here I compare multiple variants of ARFReg against the original MOA's version:

arfr_error_comparison_fried

The performance of `leaf_prediction=perceptron` and `aggregation_method='median'` led me to set this combination as the default. Thank you for this suggestion, @hmgomes.

---

### Hyper datasets

Next, I chose two variants of ARFReg and applied them to versions of the `Hyper` dataset (another well-known synthetic task) containing different kinds of concept drift. The selected versions were:

1. `leaf_prediction='mean'`, `aggregation_method='mean'`, and `weighted_vote_strategy=None`: this variant mimics the MOA implementation with its default parameters. The only major difference lies in the base learner choice (FIMT-DD in MOA and HoeffdingTreeRegressor in skmultiflow).
2. `leaf_prediction='perceptron'`, `aggregation_method='median'`, and `weighted_vote_strategy=None`: the best variant in the previous test.

#### Hyper dataset with Abrupt drifts

arfr_error_comparison_hyper_abrupt

#### Hyper dataset with Gradual drifts

arfr_error_comparison_hyper_gradual

**Comment by jacobmontiel** [comment]
> I have adapted this helper function from the previous attribute observer. Nonetheless, none of the trees actually use it.

Is this relevant for the regression case?

**Comment by smastelini** [comment]
> Is this relevant for the regression case?

This action is described in the original FIMT-DD's paper. I have checked the FIMT-DD code in MOA. The equivalent of the `remove_bad_splits` is called in case a split attempt fails:

https://github.com/Waikato/moa/blob/8b2f60d06958dfb1d2a6e1f94defb67e803b8971/moa/src/main/java/moa/classifiers/trees/FIMTDD.java#L899-L917

Nonetheless, FIMT-DD does not implement the strategy to completely disabling features as in`HoeffdingTreeRegressor`:

https://github.com/scikit-multiflow/scikit-multiflow/blob/21a0bee0f9565dafb9aa3b69f8206ee0c411a3f9/src/skmultiflow/trees/hoeffding_tree_regressor.py#L511-L543

I believe this last mentioned feature was inherited from `HoeffdingTreeClassifier`. We could possibly add a call to `remove_bad_splits` too. But in IMHO, that should not be done directly in `HoeffdingTreeRegressor`. Perhaps, in a common method to all the regression-based learning nodes. In this sense, the tree would not directly access the attribute observers, and each node would handle its memory management separately (when applicable).

What do you think?

**Comment by jacobmontiel** [comment]
> I believe this last mentioned feature was inherited from HoeffdingTreeClassifier. We could possibly add a call to remove_bad_splits too. 

Pruning the tree is desirable given the potential efficiency boost. This has been explored both in classification and regression as you mention, so I believe we should have it.

> But in IMHO, that should not be done directly in `HoeffdingTreeRegressor`. Perhaps, in a common method to all the regression-based learning nodes. In this sense, the tree would not directly access the attribute observers, and each node would handle its memory management separately (when applicable).
> 
> What do you think?

I am having trouble understanding how is this going to be triggered if the functionality is moved to the nodes. Could you elaborate on this?

**Comment by smastelini** [comment]
> I  am having trouble understanding how is this going to be triggered if the functionality is moved to the nodes. Could you elaborate on this?

I was thinking on calling a node's method, which, in turn, would access the attribute observers. The observers are private objects of the node, that's why I thought on avoiding accessing them directly from the tree.

**Comment by smastelini** [comment]
> Pruning the tree is desirable given the potential efficiency boost. This has been explored both in classification and regression as you mention, so I believe we should have it.

I added the support for pruning the E-BST attribute observers. No changes were necessary on the trees' tests, but the ARFReg's ones had to be (slightly) modified.

Now, I have the sensation that the memory-management tests (related to #230) might have been impacted. Since the trees ought to use fewer memory resources now in the attribute observers, the memory-management tests might need to be updated to ensure the size control mechanisms are effectively triggered.

**Comment by smastelini** [comment]
For completeness, I also ran some benchmarks comparing the original `HoeffdingTreeRegressor` (as in `master`) with the current version. This last one has a routine to remove potentially bad split candidates in the `NumericAttributeRegressionObserver` (as originally proposed in FIMT-DD's paper).

The following table summarizes the obtained results. No error measurements were included, since the resulting tree structures ought to be equivalent (in case of stationary streams):

image

**Pull request merged**
